apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cleaner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleaner-binding
subjects:
- kind: ServiceAccount
  name: pod-cleaner
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-cleaner-role
  apiGroup: rbac.authorization.k8s.io
