apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleaner
  namespace: default
  labels:
    app: pod-cleaner
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pod-cleaner
        spec:
          serviceAccountName: pod-cleaner
          restartPolicy: "Never"
          containers:
          - name: pod-cleaner
            image: docker.io/vilat/pod-cleaner:v1-arm
            imagePullPolicy: IfNotPresent
            command:
            - /pod-cleaner
            args:
            - --policy-config=/policy-dir/policy.yaml
            volumeMounts:
            - name: config-volume
              mountPath: /policy-dir
              readOnly: true
          volumes:
          - name: config-volume
            configMap:
              name: pod-cleaner-policy
